# Generated by Django 4.1.7 on 2023-02-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation_Type',
            fields=[
                ('pk_allocation_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Allocation Type')),
                ('code_allocation_type', models.CharField(max_length=513, verbose_name='Allocation Type Code')),
                ('desc_allocation_type', models.CharField(default=None, max_length=512, verbose_name='Allocation Type')),
            ],
            options={
                'verbose_name_plural': 'Allocation Type',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('pk_business', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Business')),
                ('desc_business', models.CharField(max_length=512, verbose_name='Business')),
            ],
            options={
                'verbose_name_plural': 'Business',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('pk_company', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Company')),
                ('desc_company', models.CharField(max_length=512, verbose_name='Companys')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('pk_department', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Department')),
                ('desc_department', models.CharField(max_length=512, verbose_name='Department')),
                ('desc_pl_group', models.CharField(default=None, max_length=512, verbose_name='P&L Group')),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Cost_Center',
            fields=[
                ('pk_cost_center', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Cost Center')),
                ('code_cost_center', models.CharField(max_length=512, verbose_name='Cost Center Code')),
                ('desc_cost_center', models.CharField(max_length=512, verbose_name='Cost Center')),
                ('fk_allocation_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.allocation_type', verbose_name='Allocation Type')),
                ('fk_business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.business', verbose_name='Business')),
                ('fk_company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.company', verbose_name='Company')),
                ('fk_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.department', verbose_name='Department')),
            ],
            options={
                'verbose_name_plural': 'Cost Center',
            },
        ),
    ]
