# Generated by Django 4.1.7 on 2023-02-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Cost_Center',
            fields=[
                ('pk_status_cost_center', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Status Cost Center')),
                ('desc_status_cost_center', models.CharField(max_length=512, verbose_name='Status Cost Center')),
            ],
            options={
                'verbose_name_plural': 'Status Cost Center',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='desc_company',
            field=models.CharField(max_length=512, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cost_center',
            name='fk_status_cost_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.status_cost_center', verbose_name='Status Cost Center'),
        ),
    ]
