# Generated by Django 4.1.7 on 2023-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0002_status_cost_center_alter_company_desc_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Product',
            fields=[
                ('pk_status_product', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Status Product')),
                ('desc_status_product', models.CharField(max_length=512, verbose_name='Status Product')),
            ],
            options={
                'verbose_name_plural': 'Status Product',
            },
        ),
    ]
