# Generated by Django 4.1.7 on 2023-02-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0003_status_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('pk_segment', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Segment')),
                ('desc_segment', models.CharField(max_length=512, verbose_name='Segment')),
            ],
            options={
                'verbose_name_plural': 'Segment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pk_product', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Product')),
                ('desc_product', models.CharField(max_length=512, verbose_name='Product')),
                ('fk_segment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.segment', verbose_name='Segment')),
                ('fk_status_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.status_product', verbose_name='Status Product')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
