# Generated by Django 4.1.7 on 2023-02-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0004_segment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Type',
            fields=[
                ('pk_access_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Access Type')),
                ('desc_access_type', models.CharField(max_length=512, verbose_name='Access Type')),
            ],
            options={
                'verbose_name_plural': 'Access Type',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('pk_city', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID City')),
                ('desc_city', models.CharField(max_length=512, verbose_name='City')),
                ('desc_state', models.CharField(default=None, max_length=512, verbose_name='State')),
                ('desc_country', models.CharField(default=None, max_length=512, verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='Contract_Type',
            fields=[
                ('pk_contract_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Contract Type')),
                ('desc_contract_type', models.CharField(max_length=512, verbose_name='Contract Type')),
            ],
            options={
                'verbose_name_plural': 'Contract Type',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pk_position', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Position')),
                ('desc_position', models.CharField(max_length=512, verbose_name='Position')),
            ],
            options={
                'verbose_name_plural': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Status_Employee',
            fields=[
                ('pk_status_employee', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Status Employee')),
                ('desc_status_employee', models.CharField(max_length=512, verbose_name='Status Employee')),
            ],
            options={
                'verbose_name_plural': 'Status Employee',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('pk_vendor', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Vendor')),
                ('desc_vendor', models.CharField(max_length=512, verbose_name='Vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('pk_employee', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Employee')),
                ('code_employee', models.IntegerField(verbose_name='Employee Code')),
                ('desc_employee', models.CharField(max_length=512, verbose_name='Employee')),
                ('date_admission', models.DateField(verbose_name='Admission Date')),
                ('date_termination', models.DateField(verbose_name='Termination Date')),
                ('fk_access_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.access_type', verbose_name='Access Type')),
                ('fk_city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.city', verbose_name='City')),
                ('fk_contract_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.contract_type', verbose_name='Contract Type')),
                ('fk_cost_center', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.cost_center', verbose_name='Cost Center')),
                ('fk_position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.position', verbose_name='Position')),
                ('fk_status_employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.status_employee', verbose_name='Status Employee')),
                ('fk_vendor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
