# Generated by Django 4.1.7 on 2023-02-21 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rateio_site', '0008_alter_access_type_desc_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fk_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
