# Generated by Django 4.1.7 on 2023-02-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0009_employee_fk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fk_employee_leader',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fk_employee_replaced_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fk_employee_replacing',
        ),
    ]
