# Generated by Django 4.1.7 on 2023-02-21 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0011_alter_employee_date_termination'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fk_employee_leader',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.employee', verbose_name='Leader'),
        ),
    ]
