# Generated by Django 4.1.7 on 2023-02-21 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0013_employee_fk_employee_replaced_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fk_employee_leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.employee', verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fk_employee_replaced_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replaced_by', to='rateio_site.employee', verbose_name='Replaced By'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fk_employee_replacing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replacing', to='rateio_site.employee', verbose_name='Replacing'),
        ),
    ]
