# Generated by Django 4.1.7 on 2023-02-21 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rateio_site', '0014_alter_employee_fk_employee_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fk_user',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
