# Generated by Django 4.1.7 on 2023-02-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0016_alter_employee_fk_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('pk_month', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Month')),
                ('desc_month', models.CharField(max_length=512, null=True, verbose_name='Month')),
                ('desc_ytd_ytg', models.CharField(max_length=512, null=True, verbose_name='YTG YTG')),
            ],
            options={
                'verbose_name_plural': 'Month',
            },
        ),
        migrations.CreateModel(
            name='Squad_Group',
            fields=[
                ('pk_squad_group', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Squad Group')),
                ('desc_squad_group', models.CharField(max_length=512, null=True, verbose_name='Squad Group')),
            ],
            options={
                'verbose_name_plural': 'Squad Group',
            },
        ),
        migrations.CreateModel(
            name='Status_Scenario',
            fields=[
                ('pk_status_scenario', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Status Scenario')),
                ('desc_status_scenario', models.CharField(max_length=512, null=True, verbose_name='Status Scenario')),
            ],
            options={
                'verbose_name_plural': 'Status Scenario',
            },
        ),
        migrations.CreateModel(
            name='Status_Squad',
            fields=[
                ('pk_status_squad', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Status Squad')),
                ('desc_status_squad', models.CharField(max_length=512, null=True, verbose_name='Status Squad')),
            ],
            options={
                'verbose_name_plural': 'Status Squad',
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('pk_squad', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Squad')),
                ('desc_squad', models.CharField(max_length=512, null=True, verbose_name='Squad')),
                ('fk_squad_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.squad_group', verbose_name='Squad Group')),
                ('fk_status_squad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.status_squad', verbose_name='Status Squad')),
            ],
            options={
                'verbose_name_plural': 'Squad',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('pk_scenario', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Scenario')),
                ('desc_scenario', models.CharField(max_length=512, null=True, verbose_name='Scenario')),
                ('fk_status_scenario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rateio_site.status_scenario', verbose_name='Status Scenario')),
            ],
            options={
                'verbose_name_plural': 'Scenario',
            },
        ),
    ]
