# Generated by Django 4.1.7 on 2023-02-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateio_site', '0017_month_squad_group_status_scenario_status_squad_squad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='desc_ytd_ytg',
            field=models.CharField(max_length=512, null=True, verbose_name='YTD YTG'),
        ),
    ]
